# Generated by Django 3.2.9 on 2026-04-24 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('ASSALTO', 'Assalto'), ('ACIDENTE', 'Acidente'), ('SUSPEITO', 'Suspeito'), ('INFRAESTRUTURA', 'Infraestrutura'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20),
        ),
        migrations.AddField(
            model_name='incident',
            name='criticality',
            field=models.CharField(blank=True, choices=[('LOW', 'Baixo'), ('MEDIUM', 'Médio'), ('HIGH', 'Alto')], max_length=10),
        ),
        migrations.AddField(
            model_name='incident',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='radius_km',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='incident',
            name='reference_point',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Aberto'), ('UNDER_REVIEW', 'Em análise'), ('RESOLVED', 'Resolvido'), ('DISMISSED', 'Descartado')], default='OPEN', max_length=20),
        ),
        migrations.AddField(
            model_name='incident',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='IncidentConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='api.incident')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_confirmations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.incident')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='incidentconfirmation',
            constraint=models.UniqueConstraint(fields=('incident', 'user'), name='unique_incident_confirmation_per_user'),
        ),
    ]
