# Generated by Django 3.2.9 on 2026-04-24 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20260424_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='incident_attachments/')),
                ('attachment_type', models.CharField(choices=[('IMAGE', 'Imagem'), ('VIDEO', 'Vídeo'), ('OTHER', 'Outro')], default='IMAGE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.incident')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
